### ISSUE TITLE
HoverPY Usage test -readthedocs and unit-testing

### ISSUE THREAD

**Issue by dushyantk** [SpectoLabs/hoverpy#1]
1. We can have a status bar while downloading Downloading https://pypi.python.org/packages/d9/03/155b3e67fe35fe5b6f4227a8d9e96a14fda828b18199800d161bcefc1359/requests-2.12.3.tar.gz#md5=0cafdecd95a46b081dd5fcfa4978db7a

2. ```warning: no files found matching 'test_requests.py' ```
still exists, don't know it it should bother the user?

3. ```python setup.py test ```
is DOWNLOADING HOVERFLY FROM https://github.com/SpectoLabs/hoverfly/releases/download/v0.9.2/hoverfly_bundle_linux_amd64.zip? (Just a query as this was not the case earlier as I remember?) And again a status message with percentage of download would help.

4. May be you can update the Output section in http://hoverpy.readthedocs.io/en/latest/installation.html, to

```testModify (hoverpy.tests.modify.testModify.TestModify) ... ok
testTemplate (hoverpy.tests.templates.testTemplates.TestTemplates) ... ok
testDecorators (hoverpy.tests.testDecorator.TestDecorators) ... ok
testCapture (hoverpy.tests.testVirtualisation.TestVirt) ... ok
testPlayback (hoverpy.tests.testVirtualisation.TestVirt) ... ok
testSimulation (hoverpy.tests.testVirtualisation.TestVirt) ... ok
testStressTest (hoverpy.tests.testVirtualisation.TestVirt) ... generating data took 4.189275
re-reading data, getting simulation, and writing it to disk took 0.795680
ok
testdbpath (hoverpy.tests.testVirtualisation.TestVirt) ... ok
```
Right now it is:

```testModify (hoverpy.tests.modify.testModify.TestModify) ... ok
testTemplate (hoverpy.tests.templates.testTemplates.TestTemplates) ... ok
testCapture (hoverpy.tests.testVirtualisation.TestVirt) ... ok
testPlayback (hoverpy.tests.testVirtualisation.TestVirt) ... ok
```
as I remember having only 4 ok in the log earlier, and that matched the document text, entry sequence is also different.

5. ```python examples/basic/basic.py's``` 
sample output can appear in the docs under "Running the examples"?

6. running 
```'python examples/readthedocs/readthedocs.py'``` 
without doing capture first still produces the same traceback. We can handle that gracefully with custom message, telling the actual reason of failure.

7. In http://hoverpy.readthedocs.io/en/latest/readthedocs.html:

```python examples/readthedocs/readthedocs.py``` 
should be formatted as code.

**Comment by shyal** [comment]
> We can have a status bar while downloading Downloading https://pypi.python.org/packages/d9/03/155b3e67fe35fe5b6f4227a8d9e96a14fda828b18199800d161bcefc1359/requests-2.12.3.tar.gz#md5=0cafdecd95a46b081dd5fcfa4978db7a

This sounds like a minor improvement. Is it necessary for launch?

> warning: no files found matching 'test_requests.py'

This is a warning only.

OK this is a minor documentation issue.

> without doing capture first still produces the same traceback. We can handle that gracefully with custom message, telling the actual reason of failure.

Possibly. Again this is not the expected usecase, but the error message could be improved.

> python examples/readthedocs/readthedocs.py

Again minor documentation issue.

Thanks for the feedback, definitely all minor stuff for now.

**Comment by dushyantk** [comment]
Yup, everything looks good otherwise.

**Comment by shyal** [comment]
This is very minor / aesthetic. Thanks.
