### ISSUE TITLE
"now obsolete"?

### ISSUE THREAD

**Issue by hangtwenty** [SpectoLabs/hoverpy#14]
The GitHub description says this is "(now obsolete)" but HoverPy is still referred to on various docs. What's the authoritative status? Deprecated and people should do their own thing with pointing to a HoverFly proxy?

**Comment by hangtwenty** [comment]
I just saw https://github.com/SpectoLabs/hoverpy/issues/13#issuecomment-402416244 and I gather the library is unmaintained. But is it obsolete just to warn of that, or has it become incompatible?

**Comment by shyal** [comment]
SpectoLabs is a zombie startup. This lib technically still has me as a maintainer, i think, but the CEO bailed a long time ago, and there's no maintenance money going to this lib.

**Comment by hangtwenty** [comment]
Got it, thank you for explaining. 

It seems like Hoverfly is maintained though?

**Comment by JohnFDavenport** [comment]
Spectolabs here. We're not putting any investment into hoverpy at the moment. Hoverfly and Hoverfly Java *and* SpectoLabs are still going concerns.
