### ISSUE TITLE
HoverPY usage test-delays, modify, urllib2

### ISSUE THREAD

**Issue by dushyantk** [SpectoLabs/hoverpy#2]
So far cannot find any catch in these examples:

Note: In http://hoverpy.readthedocs.io/en/latest/, modify_payload should nest under modify.

Following are the logs:

**delays:**

```(.venv)[dushyant@localhost hoverpy]$ python examples/delays/delays.py```
capturing responses from echo server

{u'original': u'0', u'md5': u'cfcd208495d565ef66e7dff9f98764da'}
{u'i': u'1'}
{u'original': u'2', u'md5': u'c81e728d9d4c2f636f067f89cc14862c'}
{u'i': u'3'}
{u'i': u'4'}
{u'original': u'5', u'md5': u'e4da3b7fbbce2345d7772b0674a318d5'}
{u'original': u'6', u'md5': u'1679091c5a880faf6fb5e6087eb1b2dc'}
{u'i': u'7'}
{u'i': u'8'}
{u'i': u'9'}
{u'message': u'Response delays updated.'}
{u'message': u'Response delays updated.'}
simulate

replaying delayed responses from echo server

{u'original': u'0', u'md5': u'cfcd208495d565ef66e7dff9f98764da'}
{u'i': u'1'}
{u'original': u'2', u'md5': u'c81e728d9d4c2f636f067f89cc14862c'}
{u'i': u'3'}
{u'i': u'4'}
{u'original': u'5', u'md5': u'e4da3b7fbbce2345d7772b0674a318d5'}
{u'original': u'6', u'md5': u'1679091c5a880faf6fb5e6087eb1b2dc'}
{u'i': u'7'}
{u'i': u'8'}
{u'i': u'9'}

**modify:**

```(.venv)[dushyant@localhost hoverpy]$ python examples/modify/modify.py```
something went wrong - deal with it gracefully
something went wrong - deal with it gracefully
response successfully modified, current date is 04:06:55 PM
something went wrong - deal with it gracefully
something went wrong - deal with it gracefully
response successfully modified, current date is 04:06:57 PM
response successfully modified, current date is 04:06:57 PM
something went wrong - deal with it gracefully
response successfully modified, current date is 04:06:59 PM
response successfully modified, current date is 04:06:59 PM
something went wrong - deal with it gracefully
response successfully modified, current date is 04:07:00 PM
response successfully modified, current date is 04:07:01 PM
response successfully modified, current date is 04:07:02 PM
response successfully modified, current date is 04:07:02 PM
something went wrong - deal with it gracefully
response successfully modified, current date is 04:07:04 PM
response successfully modified, current date is 04:07:04 PM
response successfully modified, current date is 04:07:05 PM
response successfully modified, current date is 04:07:05 PM
something went wrong - deal with it gracefully
something went wrong - deal with it gracefully
response successfully modified, current date is 04:07:07 PM
something went wrong - deal with it gracefully
response successfully modified, current date is 04:07:08 PM
something went wrong - deal with it gracefully
something went wrong - deal with it gracefully
something went wrong - deal with it gracefully
something went wrong - deal with it gracefully
response successfully modified, current date is 04:07:11 PM

**urllib2**

```(.venv)[dushyant@localhost hoverpy]$ python examples/urllib2eg/urllib2eg.py```
{"ip": "49.44.51.86"}

{"ip": "49.44.51.86"}

**Comment by shyal** [comment]
Point being?

**Comment by dushyantk** [comment]
I mean, everything looks good here.

Only thing is that the doc can be improved on this link: http://hoverpy.readthedocs.io/en/latest/, **modify_payload** should nest under **modify** I suppose?

**Comment by shyal** [comment]
Thanks Dushyant. Fixed.
