### ISSUE TITLE
error: (10038, 'An operation was attempted on something that is not a socket')

### ISSUE THREAD

**Issue by ChellappaSait** [SpectoLabs/hoverpy#3]
In Windows : 
    [httpd, self.stop_read], [self.stop_write], []
error: (10038, 'An operation was attempted on something that is not a socket')

Expected : It should say capture ok   , But my firewall assked for approval to get them working . I have given access. but still is not working

**Comment by shyal** [comment]
Fixed. Thanks for the report!

**Comment by shyal** [comment]
https://github.com/SpectoLabs/hoverpy/releases/tag/0.1.17

**Comment by ChellappaSait** [comment]
It works as expected in latest version
