### ISSUE TITLE
It says in test  Capture for long time With out running virtualenv 

### ISSUE THREAD

**Issue by ChellappaSait** [SpectoLabs/hoverpy#4]
With out running virtualenv -
chell@LAPTOP-M83TAKIV MINGW64 ~/oliver/hoverpy (master)
$ python setup.py test
running test
Searching for requests
Reading https://pypi.python.org/simple/requests/
Best match: requests 2.12.3
Downloading https://pypi.python.org/packages/d9/03/155b3e67fe35fe5b6f4227a8d9e96a14fda828b18199800d161bcefc1359/requests-2.12.3.tar.gz#md5=0cafdecd95a46b081dd5fcfa4978db7a
Processing requests-2.12.3.tar.gz
Writing c:\users\chell\appdata\local\temp\easy_install-gbgwbe\requests-2.12.3\setup.cfg
Running requests-2.12.3\setup.py -q bdist_egg --dist-dir c:\users\chell\appdata\local\temp\easy_install-gbgwbe\requests-2.12.3\egg-dist-tmp-atndow
warning: no files found matching 'test_requests.py'
creating c:\users\chell\oliver\hoverpy\.eggs\requests-2.12.3-py2.7.egg
Extracting requests-2.12.3-py2.7.egg to c:\users\chell\oliver\hoverpy\.eggs

Installed c:\users\chell\oliver\hoverpy\.eggs\requests-2.12.3-py2.7.egg
running egg_info
writing requirements to hoverpy.egg-info\requires.txtIt satsys in test  Capture for long time.
writing hoverpy.egg-info\PKG-INFO
writing top-level names to hoverpy.egg-info\top_level.txt
writing dependency_links to hoverpy.egg-info\dependency_links.txt
reading manifest file 'hoverpy.egg-info\SOURCES.txt'
writing manifest file 'hoverpy.egg-info\SOURCES.txt'
running build_ext
testModify (hoverpy.tests.modify.testModify.TestModify) ... FAIL
testTemplate (hoverpy.tests.templates.testTemplates.TestTemplates) ... ok
testDecorators (hoverpy.tests.testDecorator.TestDecorators) ... ok
testCapture (hoverpy.tests.testVirtualisation.TestVirt) ...
 

Issue : It satsys in test  Capture for long time.

**Comment by shyal** [comment]
Can you do an update and try again?

**Comment by ChellappaSait** [comment]
it works with  0.1.17  

Note: Version need to update in various documents.

**Comment by shyal** [comment]
> Note: Version need to update in various documents.

What do you mean by this?
