### ISSUE TITLE
ValueError: Could not start hoverfly!

### ISSUE THREAD

**Issue by ChellappaSait** [SpectoLabs/hoverpy#5]
(.venv) C:\Users\chell\hoverpy\examples\delays>python delays.py
Traceback (most recent call last):
  File "delays.py", line 10, in <module>
    with HoverPy(capture=True) as hp:
  File "C:\Users\chell\hoverpy\.venv\lib\site-packages\hoverpy-0.1.17-py2.7.egg\hoverpy\__init__.py", line 77, in __init__
    self.__start()
  File "C:\Users\chell\hoverpy\.venv\lib\site-packages\hoverpy-0.1.17-py2.7.egg\hoverpy\__init__.py", line 305, in __start
    raise ValueError("Could not start hoverfly!")
ValueError: Could not start hoverfly!

**Comment by shyal** [comment]
Hi. Could you update and try again?

C:\Users\shyal\hoverpy>"C:\Python27\python.exe" examples\delays\delays.py
capturing responses from echo server

{u'original': u'0', u'md5': u'cfcd208495d565ef66e7dff9f98764da'}
{u'i': u'1'}
{u'original': u'2', u'md5': u'c81e728d9d4c2f636f067f89cc14862c'}
{u'i': u'3'}
{u'i': u'4'}
{u'original': u'5', u'md5': u'e4da3b7fbbce2345d7772b0674a318d5'}
{u'original': u'6', u'md5': u'1679091c5a880faf6fb5e6087eb1b2dc'}
{u'i': u'7'}
{u'i': u'8'}
{u'i': u'9'}
{u'message': u'Response delays updated.'}
{u'message': u'Response delays updated.'}
simulate

replaying delayed responses from echo server

{u'original': u'0', u'md5': u'cfcd208495d565ef66e7dff9f98764da'}
{u'i': u'1'}
{u'original': u'2', u'md5': u'c81e728d9d4c2f636f067f89cc14862c'}
{u'i': u'3'}
{u'i': u'4'}
{u'original': u'5', u'md5': u'e4da3b7fbbce2345d7772b0674a318d5'}
{u'original': u'6', u'md5': u'1679091c5a880faf6fb5e6087eb1b2dc'}
{u'i': u'7'}
{u'i': u'8'}
{u'i': u'9'}

**Comment by shyal** [comment]
The examples need to be run from the project's root directory.
